---
name: Hello Web

on:
  push:
    branches: ["main"]

permissions:
  contents: read

defaults:
  run:
    working-directory: .

jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pylint

    - name: Lint with flake8
      run: |
        flake8 helloweb.py --count --show-source --statistics --max-line-length=127
    - name: Lint with pylint
      run: pylint helloweb.py

    - name: Setup buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push to Docker
      id: build_push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        provenance: false
        push: true
        tags: |
          docker.io/helloweb:latest
